// Minimal card image map - maps card names to image filenames
// Uses simple naming convention to avoid full tarot dataset dependency

const cardImageMap: Record<string, string> = {
  'The Fool': 'tc-fool',
  'The Magician': 'tc-magician',
  'The High Priestess': 'tc-high-priestess',
  'The Empress': 'tc-empress',
  'The Emperor': 'tc-emperor',
  'The Hierophant': 'tc-hierophant',
  'The Lovers': 'tc-lovers',
  'The Chariot': 'tc-chariot',
  'Strength': 'tc-strength',
  'The Hermit': 'tc-hermit',
  'Wheel of Fortune': 'tc-wheel',
  'Justice': 'tc-justice',
  'The Hanged Man': 'tc-hanged-man',
  'Death': 'tc-death',
  'Temperance': 'tc-temperance',
  'The Devil': 'tc-devil',
  'The Tower': 'tc-tower',
  'The Star': 'tc-star',
  'The Moon': 'tc-moon',
  'The Sun': 'tc-sun',
  'Judgement': 'tc-judgement',
  'The World': 'tc-world',
  'Ace of Cups': 'tc-ace-cups',
  'Two of Cups': 'tc-two-cups',
  'Three of Cups': 'tc-three-cups',
  'Four of Cups': 'tc-four-cups',
  'Five of Cups': 'tc-five-cups',
  'Six of Cups': 'tc-six-cups',
  'Seven of Cups': 'tc-seven-cups',
  'Eight of Cups': 'tc-eight-cups',
  'Nine of Cups': 'tc-nine-cups',
  'Ten of Cups': 'tc-ten-cups',
  'Ace of Pentacles': 'tc-ace-pentacles',
  'Two of Pentacles': 'tc-two-pentacles',
  'Three of Pentacles': 'tc-three-pentacles',
  'Four of Pentacles': 'tc-four-pentacles',
  'Five of Pentacles': 'tc-five-pentacles',
  'Six of Pentacles': 'tc-six-pentacles',
  'Seven of Pentacles': 'tc-seven-pentacles',
  'Eight of Pentacles': 'tc-eight-pentacles',
  'Nine of Pentacles': 'tc-nine-pentacles',
  'Ten of Pentacles': 'tc-ten-pentacles',
  'Ace of Swords': 'tc-ace-swords',
  'Two of Swords': 'tc-two-swords',
  'Three of Swords': 'tc-three-swords',
  'Four of Swords': 'tc-four-swords',
  'Five of Swords': 'tc-five-swords',
  'Six of Swords': 'tc-six-swords',
  'Seven of Swords': 'tc-seven-swords',
  'Eight of Swords': 'tc-eight-swords',
  'Nine of Swords': 'tc-nine-swords',
  'Ten of Swords': 'tc-ten-swords',
  'Ace of Wands': 'tc-ace-wands',
  'Two of Wands': 'tc-two-wands',
  'Three of Wands': 'tc-three-wands',
  'Four of Wands': 'tc-four-wands',
  'Five of Wands': 'tc-five-wands',
  'Six of Wands': 'tc-six-wands',
  'Seven of Wands': 'tc-seven-wands',
  'Eight of Wands': 'tc-eight-wands',
  'Nine of Wands': 'tc-nine-wands',
  'Ten of Wands': 'tc-ten-wands',
};

export function getCardImage(cardName: string): string {
  const filename = cardImageMap[cardName] || cardName.toLowerCase().replace(/\s+/g, '-').replace(/[^a-z-]/g, '');
  return `/tdt-v3/cards/${filename}.png`;
}
