'use client';

import { TRANSLATIONS } from './translations';
import { detectLanguageFromText, convertToHinglish, translateToHindi } from './autoTranslate';

const supportedLangs = ['en', 'hi', 'hinglish'] as const;
type SupportedLang = typeof supportedLangs[number];

function getNested(obj: any, path: string): any {
  return path.split('.').reduce((acc: any, part: string) => acc?.[part], obj);
}

function setNested(obj: any, path: string, value: any): void {
  const parts = path.split('.');
  let current = obj;
  for (let i = 0; i < parts.length - 1; i++) {
    const part = parts[i];
    if (!current[part]) {
      current[part] = {};
    }
    current = current[part];
  }
  current[parts[parts.length - 1]] = value;
}

export async function resolveTranslation(key: string, lang: string): Promise<string> {
  const normalizedLang = lang as SupportedLang;
  const entry = getNested(TRANSLATIONS, key);

  if (entry && entry[normalizedLang]) {
    return entry[normalizedLang];
  }

  if (entry?.en) {
    return entry.en;
  }

  const autoGenerated = await autoGenerateMissingTranslations(key);

  injectTranslation(key, autoGenerated);

  return autoGenerated[normalizedLang] || autoGenerated.en || key;
}

export async function generateMissingTranslation(key: string): Promise<Record<string, string>> {
  const words = key.split('.').pop() || key;
  const text = words.replace(/([A-Z])/g, ' $1').trim();

  return {
    en: text.charAt(0).toUpperCase() + text.slice(1),
    hi: await translateToHindi(text),
    hinglish: await convertToHinglish(text),
  };
}

export async function autoGenerateMissingTranslations(key: string): Promise<Record<string, string>> {
  const words = key.split('.').pop() || key;
  const text = words.replace(/([A-Z])/g, ' $1').replace(/([a-z])([A-Z])/g, '$1 $2').trim();
  const cleanedText = text.charAt(0).toUpperCase() + text.slice(1);

  const [hindi, hinglish] = await Promise.all([
    translateToHindi(cleanedText).catch(() => cleanedText),
    convertToHinglish(cleanedText).catch(() => cleanedText),
  ]);

  return {
    en: cleanedText,
    hi: hindi,
    hinglish: hinglish,
  };
}

export function injectTranslation(key: string, values: Record<string, string>): void {
  try {
    const targetLang = (values as any).lang || 'en';
    setNested((TRANSLATIONS as any)[key], key, values);
    console.log('[i18n Engine] Auto-injected:', key, targetLang);
  } catch (error) {
    console.error('[i18n Engine] Inject failed:', key, error);
  }
}

export function useSafeTranslation(lang: string) {
  return async (key: string): Promise<string> => {
    try {
      return await resolveTranslation(key, lang);
    } catch (error) {
      console.error('[i18n Engine] Resolution error:', key);
      return key;
    }
  };
}

export function createFailsafeTranslator(lang: string) {
  return (key: string, fallback?: string): string => {
    const result = getNested(TRANSLATIONS, key)?.[lang];
    if (result) return result;

    const enResult = getNested(TRANSLATIONS, key)?.en;
    if (enResult) return enResult;

    console.warn('[i18n Engine] Missing key:', key);
    return fallback || key;
  };
}

export { supportedLangs, detectLanguageFromText };